// <auto-generated />
namespace dynamics2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ganib : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ganib));
        
        string IMigrationMetadata.Id
        {
            get { return "202505080539075_ganib"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
